package com.chateausylvania.libraryapp;

public class Library
{
	int libraryID;
	String libraryName;
	Book book;
	Address address;
	LIbrarian librarian;

	// Autogenerated constructor(s)

	public Library()
	{

	}

	public Library(int libraryID, String libraryName, Book book, Address address, LIbrarian librarian)
	{
		this.libraryID = libraryID;
		this.libraryName = libraryName;
		this.book = new Book(book.getIsbn(), book.getTitle(), book.getNumPages(), book.getGenre(), book.isAudio(),
				book.getRating(), book.getAuthor());
		this.address = new Address(address.getStreetNumber(), address.getStreetName(), address.getCity(),
				address.getCountry(), address.getPostcode());
		this.librarian = new LIbrarian(librarian.getEmployeeID(), librarian.getName(), librarian.getSpecialty(),
				librarian.getAddress());
	}
	// Autogenerated getters and setters

	/**
	 * @return the libraryID
	 */
	public int getLibraryID()
	{
		return libraryID;
	}

	/**
	 * @param libraryID the libraryID to set
	 */
	public void setLibraryID(int libraryID)
	{
		this.libraryID = libraryID;
	}

	/**
	 * @return the libraryName
	 */
	public String getLibraryName()
	{
		return libraryName;
	}

	/**
	 * libraryName the libraryName to set
	 */
	public void setLibraryName(String libraryName)
	{
		this.libraryName = libraryName;
	}

	/**
	 * @return the book
	 */
	public Book getBook()
	{
		return new Book(book.getIsbn(), book.getTitle(), book.getNumPages(), book.getGenre(), book.isAudio(),
				book.getRating(), book.getAuthor());
	}

	/**
	 * @param book the book to set
	 */
	public void setBook(Book book)
	{
		this.book = new Book(book.getIsbn(), book.getTitle(), book.getNumPages(), book.getGenre(), book.isAudio(),
				book.getRating(), book.getAuthor());
		;
	}

	/**
	 * @return the address
	 */
	public Address getAddress()
	{
		return new Address(address.getStreetNumber(), address.getStreetName(), address.getCity(), address.getCountry(),
				address.getPostcode());
	}

	/**
	 * @param address the address to set
	 */
	public void setAddress(Address address)
	{
		this.address = new Address(address.getStreetNumber(), address.getStreetName(), address.getCity(),
				address.getCountry(), address.getPostcode());
	}

	/**
	 * @return the librarian
	 */
	public LIbrarian getLibrarian()
	{
		return librarian = new LIbrarian(librarian.getEmployeeID(), librarian.getName(), librarian.getSpecialty(),
				librarian.getAddress());
	}

	/**
	 * @param librarian the librarian to set
	 */
	public void setLibrarian(LIbrarian librarian)
	{
		this.librarian = librarian = new LIbrarian(librarian.getEmployeeID(), librarian.getName(),
				librarian.getSpecialty(), librarian.getAddress());
	}

	// Autogenerated toString

	@Override
	public String toString()
	{
		return "Library [libraryID=" + libraryID + ", libraryName=" + libraryName + ", book=" + book + ", address="
				+ address + ", librarian=" + librarian + "]";
	}

}
